### ISSUE TITLE
Something went wrong on Badge 

### ISSUE THREAD

**Issue by Chhunneng** [holopin/integration-support#3]
there is one error of the badge that I don't know what happened on that?

Here is on console
```
GET https://assets.holopin.io/hf2023levels/levelundefined-blue-0-0-0.webp 403 (Forbidden)
```
<img width="498" alt="Screenshot 2023-10-24 at 15 34 03" src="https://github.com/holopin/integration-support/assets/47348453/034ddee2-a28b-4895-8eee-a03f87f46973">
<img width="611" alt="Screenshot 2023-10-24 at 15 34 21" src="https://github.com/holopin/integration-support/assets/47348453/4314d23a-6a05-46a4-9dbc-f2ab9b729da3">

<img width="1273" alt="Screenshot 2023-10-24 at 15 29 40" src="https://github.com/holopin/integration-support/assets/47348453/d99f7abd-b8e2-4f3f-b418-fae92c42eff2">
<img width="1001" alt="Screenshot 2023-10-24 at 15 30 22" src="https://github.com/holopin/integration-support/assets/47348453/9bb948fa-58ab-4f2d-ae06-15ab355f9b81">
<img width="432" alt="Screenshot 2023-10-24 at 15 30 39" src="https://github.com/holopin/integration-support/assets/47348453/68ae8b65-5ad4-4b03-b93c-30ffd4e4ed77">

**Comment by rphi** [comment]
Hi Chrea, not entirely sure how that happened, but I've fixed up your badge and the image is now loading, along with your board. Cheers, and good luck with the rest of Hacktoberfest! 🦖

![chrea's board](https://boards.holopin.io/chhunneng)

**Comment by Chhunneng** [comment]
Thank for you checking. But the problem still occurs on board if I log in. but if I log out I be able to see it.


<img width="599" alt="Screenshot 2023-10-25 at 9 18 31" src="https://github.com/holopin/integration-support/assets/47348453/754adc5a-ae55-4e48-98d1-4d719f753fb6">
<img width="912" alt="Screenshot 2023-10-25 at 9 19 49" src="https://github.com/holopin/integration-support/assets/47348453/65e05f5d-2e5a-4d45-a12d-aeab08d812fa">


<img width="781" alt="Screenshot 2023-10-25 at 9 15 45" src="https://github.com/holopin/integration-support/assets/47348453/5f31a5c4-230b-4c74-b986-cd99af9eaf2a">
<img width="957" alt="Screenshot 2023-10-25 at 9 17 09" src="https://github.com/holopin/integration-support/assets/47348453/2a209495-1d4b-4efa-aaf3-71758eb499da">

**Comment by Chhunneng** [comment]
@rphi
